### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by yakovlevkll** [vuepress/vuepress.github.io#4]
Hello,

Thank you all for your awesome work!

I found "Edit this page on Github" links are broken on every plugin page. It resolves to something like

`https://github.com/vuepress/vuepress.github.io/edit/master/docs/en/plugins/copyright.md`

**Comment by meteorlxy** [comment]
Thanks for reporting.

Seems that `vuepress-plugin-redirect` broke the links. @Shigma

**Comment by meteorlxy** [comment]
Seems that this issue has been fixed.

> Source code has been migrated to [this repo](https://github.com/vuepress/vuepress-contrib)
