### ISSUE TITLE
Would you mind transfer this group to Vue team

### ISSUE THREAD

**Issue by ulivz** [vuepress/vuepress.github.io#5]
Thank you for your involvement in the maintenance of VuePress in the past. If you are fading out now, would you mind handing over this group to the Vue team? Thanks.

ref: https://github.com/vuejs/vuepress/issues/1726

**Comment by meteorlxy** [comment]
Sorry to missed the announcement. We are still here :smile:

Closing as souce code has been migrated to [this repo](https://github.com/vuepress/vuepress-contrib)
